server:
  port: 9000
spring:
  application:
    name: cards
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    h2:
      console:
        enabled: true
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
      show-sql: true
  config:
    import:
      - "application_prod.yml"
      - "application_qa.yml"
  profiles:
    active:
      - "qa"

build:
  version: "3.0"

cards:
  message: "Welcome to cards related local APIs "
  contactDetails:
    name: "Hashim Hani - Application Support"
    email: "e.hashimkilani@gmail.com"
  onCallSupport:
    - (+20) 1141679790
    - (555) 523-1345