server:
  port: 8071

spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #    active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/serahawi/microservices_project_configurations.git"
          clone-on-start: true
          force-pull: true
          default-label: main
          timeout: 5
#        native:
#          search-locations: "classpath:/config"
  rabbitmq:
    host: rabbit
    port: 5672
    username: guest
    password: guest

encrypt:
  key: "X3Q1KLNVJOPWVH3ON9V43O2GH"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true